# Generated by Django 3.1 on 2020-09-02 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200902_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=8, validators=[django.core.validators.MinValueValidator(0.99)]),
        ),
    ]
