# Generated by Django 3.1 on 2020-09-05 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200905_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
